### ISSUE TITLE
"cron: panic running job: runtime error: index out of range [2] with length 0" when running planned config 

### ISSUE THREAD

**Issue by FxllenCode** [maxisam/mgob#45]
Hello!

Thanks for the awesome project! Unfortunately I'm getting a strange issue when running my plan in mgob. Below is the full stack trace I am getting:

```
2022-12-13T15:30:00.678233506Z 2022/12/13 15:30:00 cron: panic running job: runtime error: index out of range [2] with length 0
2022-12-13T15:30:00.678252737Z goroutine 55 [running]:
2022-12-13T15:30:00.678256416Z github.com/robfig/cron.(*Cron).runWithRecovery.func1()
2022-12-13T15:30:00.678259563Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:161 +0x69
2022-12-13T15:30:00.678262770Z panic({0xc05be0, 0xc000298210})
2022-12-13T15:30:00.678265786Z 	/usr/local/go/src/runtime/panic.go:884 +0x212
2022-12-13T15:30:00.678268855Z github.com/stefanprodan/mgob/pkg/backup.getDumpedDocMap({0xc000480000, 0x2edf})
2022-12-13T15:30:00.678271933Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/local.go:63 +0x245
2022-12-13T15:30:00.678275185Z github.com/stefanprodan/mgob/pkg/backup.dump({{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, {0xc00028e140, 0xa}, ...}, ...}, ...)
2022-12-13T15:30:00.678278469Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/local.go:35 +0x630
2022-12-13T15:30:00.678281517Z github.com/stefanprodan/mgob/pkg/backup.Run({{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, {0xc00028e140, 0xa}, ...}, ...}, ...)
2022-12-13T15:30:00.678293129Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/backup.go:22 +0x1f8
2022-12-13T15:30:00.678296566Z github.com/stefanprodan/mgob/pkg/scheduler.backupJob.Run({{0xc000298050, 0x6}, {{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, ...}, ...}, ...})
2022-12-13T15:30:00.678299714Z 	/go/src/github.com/stefanprodan/mgob/pkg/scheduler/scheduler.go:92 +0x13b
2022-12-13T15:30:00.678302752Z github.com/robfig/cron.(*Cron).runWithRecovery(0xc0000607d0?, {0xe15420?, 0xc0002d0000?})
2022-12-13T15:30:00.678305785Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:165 +0x62
2022-12-13T15:30:00.678308848Z created by github.com/robfig/cron.(*Cron).run
2022-12-13T15:30:00.678311862Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:199 +0x7b2
2022-12-13T15:35:00.047428329Z time="2022-12-13T15:35:00Z" level=info msg="Backup started" plan=config
2022-12-13T15:35:00.599743667Z 2022/12/13 15:35:00 cron: panic running job: runtime error: index out of range [2] with length 0
2022-12-13T15:35:00.599766494Z goroutine 59 [running]:
2022-12-13T15:35:00.599770908Z github.com/robfig/cron.(*Cron).runWithRecovery.func1()
2022-12-13T15:35:00.599774493Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:161 +0x69
2022-12-13T15:35:00.599777971Z panic({0xc05be0, 0xc000298288})
2022-12-13T15:35:00.599781180Z 	/usr/local/go/src/runtime/panic.go:884 +0x212
2022-12-13T15:35:00.599784459Z github.com/stefanprodan/mgob/pkg/backup.getDumpedDocMap({0xc000483000, 0x2edf})
2022-12-13T15:35:00.599787726Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/local.go:63 +0x245
2022-12-13T15:35:00.599791004Z github.com/stefanprodan/mgob/pkg/backup.dump({{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, {0xc00028e140, 0xa}, ...}, ...}, ...)
2022-12-13T15:35:00.599794399Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/local.go:35 +0x630
2022-12-13T15:35:00.599797609Z github.com/stefanprodan/mgob/pkg/backup.Run({{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, {0xc00028e140, 0xa}, ...}, ...}, ...)
2022-12-13T15:35:00.599801026Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/backup.go:22 +0x1f8
2022-12-13T15:35:00.599816853Z github.com/stefanprodan/mgob/pkg/scheduler.backupJob.Run({{0xc000298050, 0x6}, {{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, ...}, ...}, ...})
2022-12-13T15:35:00.599819484Z 	/go/src/github.com/stefanprodan/mgob/pkg/scheduler/scheduler.go:92 +0x13b
2022-12-13T15:35:00.599821970Z github.com/robfig/cron.(*Cron).runWithRecovery(0xc000064fd0?, {0xe15420?, 0xc0002d0000?})
2022-12-13T15:35:00.599824489Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:165 +0x62
2022-12-13T15:35:00.599826958Z created by github.com/robfig/cron.(*Cron).run
2022-12-13T15:35:00.599829386Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:199 +0x7b2
2022-12-13T15:40:00.067217384Z time="2022-12-13T15:40:00Z" level=info msg="Backup started" plan=config
2022-12-13T15:40:00.653024694Z 2022/12/13 15:40:00 cron: panic running job: runtime error: index out of range [2] with length 0
2022-12-13T15:40:00.653054720Z goroutine 63 [running]:
2022-12-13T15:40:00.653061929Z github.com/robfig/cron.(*Cron).runWithRecovery.func1()
2022-12-13T15:40:00.653066290Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:161 +0x69
2022-12-13T15:40:00.653070674Z panic({0xc05be0, 0xc00003a708})
2022-12-13T15:40:00.653074772Z 	/usr/local/go/src/runtime/panic.go:884 +0x212
2022-12-13T15:40:00.653079045Z github.com/stefanprodan/mgob/pkg/backup.getDumpedDocMap({0xc000396000, 0x2edf})
2022-12-13T15:40:00.653083237Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/local.go:63 +0x245
2022-12-13T15:40:00.653087520Z github.com/stefanprodan/mgob/pkg/backup.dump({{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, {0xc00028e140, 0xa}, ...}, ...}, ...)
2022-12-13T15:40:00.653091872Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/local.go:35 +0x630
2022-12-13T15:40:00.653096064Z github.com/stefanprodan/mgob/pkg/backup.Run({{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, {0xc00028e140, 0xa}, ...}, ...}, ...)
2022-12-13T15:40:00.653100411Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/backup.go:22 +0x1f8
2022-12-13T15:40:00.653104654Z github.com/stefanprodan/mgob/pkg/scheduler.backupJob.Run({{0xc000298050, 0x6}, {{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, ...}, ...}, ...})
2022-12-13T15:40:00.653108971Z 	/go/src/github.com/stefanprodan/mgob/pkg/scheduler/scheduler.go:92 +0x13b
2022-12-13T15:40:00.653113197Z github.com/robfig/cron.(*Cron).runWithRecovery(0xc000064fd0?, {0xe15420?, 0xc0002d0000?})
2022-12-13T15:40:00.653117434Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:165 +0x62
2022-12-13T15:40:00.653121624Z created by github.com/robfig/cron.(*Cron).run
2022-12-13T15:40:00.653125759Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:199 +0x7b2
2022-12-13T15:45:00.068879257Z time="2022-12-13T15:45:00Z" level=info msg="Backup started" plan=config
2022-12-13T15:45:00.647122041Z 2022/12/13 15:45:00 cron: panic running job: runtime error: index out of range [2] with length 0
2022-12-13T15:45:00.647141503Z goroutine 36 [running]:
2022-12-13T15:45:00.647145794Z github.com/robfig/cron.(*Cron).runWithRecovery.func1()
2022-12-13T15:45:00.647149450Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:161 +0x69
2022-12-13T15:45:00.647153686Z panic({0xc05be0, 0xc00003a780})
2022-12-13T15:45:00.647158551Z 	/usr/local/go/src/runtime/panic.go:884 +0x212
2022-12-13T15:45:00.647163503Z github.com/stefanprodan/mgob/pkg/backup.getDumpedDocMap({0xc000399000, 0x2edf})
2022-12-13T15:45:00.647168385Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/local.go:63 +0x245
2022-12-13T15:45:00.647172055Z github.com/stefanprodan/mgob/pkg/backup.dump({{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, {0xc00028e140, 0xa}, ...}, ...}, ...)
2022-12-13T15:45:00.647184427Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/local.go:35 +0x630
2022-12-13T15:45:00.647188333Z github.com/stefanprodan/mgob/pkg/backup.Run({{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, {0xc00028e140, 0xa}, ...}, ...}, ...)
2022-12-13T15:45:00.647191942Z 	/go/src/github.com/stefanprodan/mgob/pkg/backup/backup.go:22 +0x1f8
2022-12-13T15:45:00.647195428Z github.com/stefanprodan/mgob/pkg/scheduler.backupJob.Run({{0xc000298050, 0x6}, {{0xc000298050, 0x6}, {{0x0, 0x0}, {0xc00028e100, 0xd}, {0x0, 0x0}, ...}, ...}, ...})
2022-12-13T15:45:00.647199061Z 	/go/src/github.com/stefanprodan/mgob/pkg/scheduler/scheduler.go:92 +0x13b
2022-12-13T15:45:00.647202831Z github.com/robfig/cron.(*Cron).runWithRecovery(0xc0000617d0?, {0xe15420?, 0xc0002d0000?})
2022-12-13T15:45:00.647206330Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:165 +0x62
2022-12-13T15:45:00.647209779Z created by github.com/robfig/cron.(*Cron).run
2022-12-13T15:45:00.647213229Z 	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:199 +0x7b2
```

In case it helps, here is my config (with some data redacted):
```yml
scheduler:
  cron: "*/5 * * * *"
  retention: 12
  timeout: 15
target:
  host: "192.168.86.68"
  port: 27017
  database: ""
  username: "[REDACTED"
  password: "[REDACTED]"
  # add custom params to mongodump (eg. Auth or SSL support), leave blank if not needed
  # params: "--authenticationDatabase admin"
  # disable gzip compression
  noGzip: false
retry:
  # number of retries
  attempts: 3
  # backoff factor  * (2 ^ attemptCount) seconds
  backoffFactor: 60
validation:
  database:
    host: "srv-captain--mongodb"
    port: 27017
    username: "[REDACTED]"
    password: "[REDACTED]"
    # params: "--authenticationDatabase admin"
    noGzip: false
    database: test_restore # database name for restore
```

I'm not sure what's wrong here (or what's  up with the stack trace) so asking for some help here! Thanks! :raised_hands:

**Comment by maxisam** [comment]
> cron: panic running job: runtime error: index out of range [2] with length 0

base on this line 

I think your config somehow doesn't work. But I have no idea why with the info you provided

`

**Comment by maxisam** [comment]
close for now, welcome to reopen if needed
